### PR TITLE
update to v0.6.2

### PR DESCRIPTION
**Pull request by iblislin**

### CODE REVIEW

**Comment by lwhsu** [comment]
Looks good to me!  Please submit a problem report to FreeBSD.

**Comment by lwhsu** [comment]
BTW you can directly file a ticket on bugs.freebsd.org.  This repository is a working area before we have Julia in the ports tree.  You can still use this as your working area, and push directly to it.

**Comment by iblislin** [comment]
will send PR later.
I'm still running `testport` on my local box.

**Comment by iblislin** [comment]
filed here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224421

**Pull request merged**
